"""Regenerate deterministic synthetic PDF and raster of the same layout."""

import hashlib
import json
from pathlib import Path

import pypdfium2
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


HERE = Path(__file__).resolve().parent
PDF = HERE / "demo-bill-2026-08.pdf"
PNG = HERE / "demo-bill-2026-08.png"
SCAN_PDF = HERE / "demo-bill-2026-08-scan.pdf"
MANIFEST = HERE / "manifest.json"


def main() -> None:
    pdf = canvas.Canvas(str(PDF), pagesize=(595, 842), invariant=1, pageCompression=0)
    pdf.setTitle("Synthetic demo bill v1")
    pdf.setAuthor("VK Hackathon synthetic fixture")
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, 790, "DEMO-BILL-V1")
    pdf.setFont("Helvetica", 12)
    lines = [
        "PERIOD: 2026-08",
        "ISSUER: Demo Housing Organization",
        "ACCOUNT: 000123",
        "ADDRESS: Demo City, Example Street 1, Flat 1",
        "SERVICE | QTY | TARIFF | CHARGE",
        "Cold water (m3) | 5.000000 | 40.000000 | 200.00",
        "CURRENT CHARGES: 200.00",
        "OPENING BALANCE: 0.00",
        "PAYMENTS CREDITED: 0.00",
        "PENALTIES: 0.00",
        "OTHER ACCOUNT CHANGES: 0.00",
        "CLOSING BALANCE: 200.00",
        "TOTAL DUE: 200.00",
    ]
    for index, line in enumerate(lines):
        pdf.drawString(50, 755 - index * 36, line)
    pdf.save()
    with pypdfium2.PdfDocument(PDF.read_bytes()) as document:
        image = document[0].render(scale=2).to_pil()
        image.save(PNG, format="PNG", optimize=False)
        scan = canvas.Canvas(str(SCAN_PDF), pagesize=(595, 842), invariant=1, pageCompression=0)
        scan.setTitle("Synthetic image-only demo bill v1")
        scan.drawImage(ImageReader(image.convert("RGB")), 0, 0, width=595, height=842)
        scan.save()
    samples = []
    for name, media_type, representation, period, charge, origin in (
        (PDF.name, "application/pdf", "text_pdf", "2026-08", "200.00", "Generated by generate_demo_documents.py from the English DEMO-BILL-V1 test layout"),
        (PNG.name, "image/png", "raster_of_text_pdf", "2026-08", "200.00", "Rendered from demo-bill-2026-08.pdf by pypdfium2; synthetic scan, not a phone photo"),
        (SCAN_PDF.name, "application/pdf", "image_only_pdf", "2026-08", "200.00", "Image-only PDF made from the synthetic raster; no text layer"),
        ("water-2026-08.json", "application/json", "canonical_bill_data", "2026-08", "200.00", "TECHNICAL_SPEC.md section 7.7 canonical BillData"),
        ("water-2026-09.json", "application/json", "canonical_bill_data", "2026-09", "270.00", "TECHNICAL_SPEC.md section 7.7 September modification"),
        ("water-comparison.json", "application/json", "expected_comparison", None, None, "TECHNICAL_SPEC.md sections 7.7 and 9.7 mathematical expectation"),
    ):
        data = (HERE / name).read_bytes()
        samples.append({
            "file": name, "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data),
            "media_type": media_type, "representation": representation,
            "template_id": "demo-bill-v1" if media_type != "application/json" else None,
            "expected_fields": {"period": period, "charge_amount": charge} if period else {
                "delta_current_charges": "70.00", "quantity_effect": "40.00", "tariff_effect": "30.00"
            },
            "origin": origin, "is_synthetic": True,
        })
    MANIFEST.write_text(json.dumps({"schema_version": "1.0", "samples": samples}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
