/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/max": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authenticateMax"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Enabled only in dev/demo with DEMO_AUTH_ENABLED=true. */
        post: operations["authenticateDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Enabled only with APP_MODE=preview and PREVIEW_AUTH_ENABLED=true. No request body or client-selected identity. Creates a distinct guest owner and session on every call in the isolated preview database. */
        post: operations["authenticatePreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/aggregate-consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Explicit, revocable use of confirmed real receipt service metrics for city aggregates. */
        put: operations["updateAggregateConsent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Unknown topic and clarification are successful structured results. */
        post: operations["createAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/answers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getAnswer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/dialog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description One step of the server-side dialogue shared with the MAX chat. The server keeps the pending question, offered options, service, city and selected house; a clarification is answered by an option value, its label, its number or plain text. Contact questions look up the house by address in HouseScore and Dominfo (historical supplier candidates, not verified contracts). Nothing is sent to any organization. */
        post: operations["assistantDialog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReceipts"];
        put?: never;
        /** @description Rejected with PREVIEW_SYNTHETIC_ONLY in preview mode; import /receipts/demo instead. */
        post: operations["uploadReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createManualReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importDemoReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getReceipt"];
        put?: never;
        post?: never;
        /** @description Idempotent deletion; absent or foreign ID also returns 204. */
        delete: operations["deleteReceipt"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}/city-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** @description Exact city/month/service/scope/segment/unit cohort; numeric values suppressed below five distinct real opted-in users. */
        get: operations["getCityComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preview/receipts/{id}/city-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** @description Preview-only fixed synthetic cohort for one confirmed owner receipt. This never reads or changes the real opted-in city cohort. */
        get: operations["getPreviewCityComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["editReceipt"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["explainReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** @description Authenticated bytes, Content-Disposition attachment; never a public URL. */
        get: operations["getReceiptSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}/pages/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                page: components["parameters"]["Page"];
            };
            cookie?: never;
        };
        get: operations["getReceiptPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["compareReceipts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getDraft"];
        put: operations["editDraft"];
        post?: never;
        delete: operations["deleteDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/max/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verify secret, validate event, atomically deduplicate normalized payload into inbox and acknowledge promptly. Schema of MAX updates must be confirmed against official docs before implementation; no update_id assumed. */
        post: operations["receiveMaxWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Id: string;
        /** Format: date-time */
        Timestamp: string;
        Period: string;
        Money: string;
        Profile: {
            /** @enum {string} */
            role: "owner" | "tenant" | "other";
            territory_id: string | null;
            onboarding_completed: boolean;
            privacy_notice_version: string | null;
            privacy_acknowledged_at: components["schemas"]["Timestamp"] | null;
            aggregate_opt_in: boolean;
        };
        AggregateConsentRequest: {
            enabled: boolean;
        };
        AggregateConsentView: {
            aggregate_opt_in: boolean;
        };
        CityComparisonView: {
            /** @enum {string} */
            status: "available" | "insufficient_data" | "ambiguous_city" | "ineligible";
            city: string | null;
            period: string | null;
            service_code: string;
            unit: string | null;
            /** @enum {string} */
            metric: "charge_amount" | "tariff";
            sample_size: number | null;
            average: string | null;
            median: string | null;
            /** @constant */
            provenance: "confirmed_opted_in_real_receipts";
        };
        PreviewCityComparisonView: {
            /** @enum {string} */
            status: "available" | "insufficient_data" | "ambiguous_city" | "ineligible";
            city: string | null;
            city_label: string | null;
            period: string | null;
            service_code: string;
            scope: string | null;
            segment_key: string | null;
            unit: string | null;
            /** @enum {string} */
            metric: "charge_amount" | "tariff";
            sample_size: number | null;
            average: string | null;
            median: string | null;
            receipt_value: string | null;
            difference_from_average: string | null;
            difference_percent: string | null;
            comparison: ("above" | "equal" | "below") | null;
            explanation: string | null;
            /** @constant */
            provenance: "synthetic_preview_cohort";
        };
        User: {
            id: components["schemas"]["Id"];
        };
        UserAndProfile: {
            user: components["schemas"]["User"];
            profile: components["schemas"]["Profile"];
        };
        AuthResponse: {
            /** @description Opaque 60-minute bearer; never put in URL/logs. */
            access_token: string;
            /** @constant */
            token_type: "bearer";
            /** @constant */
            expires_in: 3600;
            user: components["schemas"]["User"];
            profile: components["schemas"]["Profile"];
        };
        MaxAuthRequest: {
            init_data: string;
        };
        DemoAuthRequest: {
            access_code: string;
            /** @enum {string} */
            identity: "reviewer_a" | "reviewer_b";
        };
        UpdateProfileRequest: {
            /** @enum {string} */
            role: "owner" | "tenant" | "other";
            territory_id: string | null;
            privacy_notice_version: string;
            /** @constant */
            privacy_acknowledged: true;
        };
        Meta: {
            api_version: string;
            engine_version: string | null;
            knowledge_version: string | null;
            /** @enum {string} */
            mode: "dev" | "demo" | "preview" | "production";
            limits: {
                upload_max_bytes: number;
                pdf_max_pages: number;
                receipt_retention_days: number;
                source_retention_days: number;
            };
            features: {
                /** @constant */
                voice: false;
                /** @constant */
                external_submission: false;
                receipt_ocr: boolean;
                comparison: boolean;
                engine_stub: boolean;
                demo_auth: boolean;
                dialog?: boolean;
                /** @description HouseScore key configured; cached houses still work without it. */
                house_lookup?: boolean;
            };
            privacy_notice: {
                version: string;
                text: string;
            };
        };
        Catalog: {
            territories: components["schemas"]["CatalogItem"][];
            organizations: components["schemas"]["CatalogItem"][];
            topics: components["schemas"]["CatalogItem"][];
            service_codes: string[];
            units: string[];
            document_kinds: components["schemas"]["DocumentKind"][];
            demo_receipts: {
                fixture_id: string;
                label: string;
                description: string;
            }[];
        };
        AnswerContext: {
            territory_id: string | null;
            /** @enum {string|null} */
            role: "owner" | "tenant" | "other" | null;
            topic_id: string | null;
            organization_id: string | null;
            service_code: string | null;
            document_kind: string | null;
            receipt_id: components["schemas"]["Id"] | null;
            receipt_revision: number | null;
        };
        AnswerRequest: {
            question: string;
            context: components["schemas"]["AnswerContext"];
        };
        AnswerView: {
            id: components["schemas"]["Id"];
            created_at: components["schemas"]["Timestamp"];
            stale: boolean;
            stale_reasons: ("receipt_changed" | "source_expired" | "knowledge_updated")[];
            /** @enum {string} */
            dataset_kind: "synthetic" | "user_provided" | "public_reference";
            status: components["schemas"]["status"];
            text: components["schemas"]["text"];
            topic_id: components["schemas"]["topic_id"];
            steps: components["schemas"]["steps"];
            sources: components["schemas"]["sources"];
            actions: components["schemas"]["actions"];
            clarification: components["schemas"]["clarification"];
            limitations: components["schemas"]["limitations"];
            knowledge_version: components["schemas"]["knowledge_version"];
            receipt_ref: components["schemas"]["receipt_ref"];
        };
        ReceiptView: {
            id: components["schemas"]["Id"];
            /** @enum {string} */
            status: "queued" | "processing" | "needs_review" | "confirmed" | "failed";
            revision: number;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            /** @enum {string} */
            dataset_kind: "synthetic" | "user_provided";
            /** @enum {string|null} */
            extraction_outcome: "recognized" | "partial" | "manual_required" | null;
            bill_data: components["schemas"]["BillData.schema"];
            field_evidence: components["schemas"]["FieldEvidence.schema"][];
            issues: components["schemas"]["Issue.schema"][];
            document: {
                available: boolean;
                /** @enum {string|null} */
                mime_type: "application/pdf" | "image/jpeg" | "image/png" | null;
                page_count: number | null;
                expires_at: components["schemas"]["Timestamp"] | null;
            };
            job: {
                id: components["schemas"]["Id"];
                /** @enum {string} */
                state: "queued" | "running" | "succeeded" | "failed";
                stage: string | null;
            } | null;
            confirmed_at: components["schemas"]["Timestamp"] | null;
            engine_version: string | null;
        };
        ReceiptSummary: {
            id: components["schemas"]["Id"];
            /** @enum {string} */
            status: "queued" | "processing" | "needs_review" | "confirmed" | "failed";
            revision: number;
            period: components["schemas"]["Period"] | null;
            issuer_name: string | null;
            document_total_due: components["schemas"]["Money"] | null;
            /** @enum {string} */
            dataset_kind: "synthetic" | "user_provided";
            created_at: components["schemas"]["Timestamp"];
            source_available: boolean;
        };
        ReceiptQueued: {
            receipt: components["schemas"]["ReceiptView"];
            job_id: components["schemas"]["Id"];
        };
        ReceiptList: {
            items: components["schemas"]["ReceiptSummary"][];
            next_cursor: string | null;
        };
        /** @description Full BillData snapshot; server sets manual-v1 template, unsupported settlement formula and line calculation kinds. */
        ManualReceiptRequest: {
            bill_data: components["schemas"]["BillData.schema"];
        };
        DemoReceiptRequest: {
            fixture_id: string;
        };
        /** @description Full BillData snapshot. Server preserves template_id, template_version, settlement.formula_kind and calculation_kind for existing line IDs; new lines use document_amount. */
        EditReceiptRequest: {
            expected_revision: number;
            bill_data: components["schemas"]["BillData.schema"];
        };
        ConfirmReceiptRequest: {
            expected_revision: number;
            acknowledged_warning_codes: string[];
        };
        RetryReceiptRequest: {
            expected_revision: number;
        };
        Job: {
            id: components["schemas"]["Id"];
            kind: string;
            /** @enum {string} */
            state: "queued" | "running" | "succeeded" | "failed";
            stage: string | null;
            receipt_id: components["schemas"]["Id"] | null;
            error: components["schemas"]["JobError"] | null;
            updated_at: components["schemas"]["Timestamp"];
        };
        JobError: {
            code: string;
            message: string;
            retryable: boolean;
        };
        ReceiptRef: {
            id: components["schemas"]["Id"];
            revision: number;
        };
        CompareRequest: {
            left: components["schemas"]["ReceiptRef"];
            right: components["schemas"]["ReceiptRef"];
            identity_acknowledged: boolean;
        };
        ComparisonView: {
            /** @enum {string} */
            dataset_kind: "synthetic" | "user_provided";
            status: components["schemas"]["properties-status"];
            older: components["schemas"]["PeriodReceiptRef"];
            newer: components["schemas"]["PeriodReceiptRef"];
            engine_version: components["schemas"]["engine_version"];
            knowledge_version: components["schemas"]["knowledge_version"];
            delta_current_charges: components["schemas"]["delta_current_charges"];
            delta_adjustments: components["schemas"]["delta_adjustments"];
            delta_total_due: components["schemas"]["delta_total_due"];
            lines: components["schemas"]["lines"];
            settlement_deltas: components["schemas"]["settlement_deltas"];
            unexplained_delta: components["schemas"]["unexplained_delta"];
            issues: components["schemas"]["issues"];
            actions: components["schemas"]["actions"];
        };
        CreateDraftRequest: {
            topic_id: string;
            organization_id: string | null;
            receipt_refs: components["schemas"]["ReceiptRef"][];
            line_id: components["schemas"]["Id"] | null;
            user_question: string;
        };
        EditDraftRequest: {
            expected_revision: number;
            text: string;
        };
        DraftView: {
            id: components["schemas"]["Id"];
            revision: number;
            text: string;
            recipient: components["schemas"]["recipient"];
            actions: components["schemas"]["actions"];
            receipt_refs: components["schemas"]["ReceiptRef"][];
            stale: boolean;
            knowledge_version: string;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        DialogRequest: {
            /** @description Free text typed by the user. */
            message?: string | null;
            /** @description Option value from the previous reply, or a quick start such as topic:supplier_contacts. */
            choice?: string | null;
            /** @description Start a new question; city and house stay remembered. */
            reset?: boolean;
            receipt_id?: components["schemas"]["Id"] | null;
            receipt_revision?: number | null;
        };
        DialogOption: {
            value: string;
            label: string;
        };
        DialogLink: {
            label: string;
            url: string;
        };
        HouseCard: {
            /** @description Topic-specific hint shown before the card (readings */
            intro: string | null;
            address: string;
            fias_guid: string;
            service: {
                /** @enum {string} */
                code: "heating" | "hot_water" | "cold_water" | "sewerage" | "electricity" | "gas" | "waste" | "management";
                name: string;
                /** @enum {string} */
                status: "candidate" | "verified" | "unknown" | "not_available" | "management";
                note: string | null;
            };
            provider: null | {
                name: string;
                inn: string | null;
                website: string | null;
                contact_url: string | null;
                contact_label: string | null;
            };
            management: {
                name: string | null;
                phone: string | null;
                email: string | null;
                fetched_at: string;
            };
            source: {
                url: string | null;
                reviewed_at: string | null;
                record_start_at_utc: string | null;
            };
            links: components["schemas"]["DialogLink"][];
            warnings: string[];
        };
        DialogReply: {
            /** @enum {string} */
            status: "answered" | "needs_input" | "unsupported" | "error";
            text: string;
            options: components["schemas"]["DialogOption"][];
            card: components["schemas"]["HouseCard"] | null;
            links: components["schemas"]["DialogLink"][];
            sources: components["schemas"]["sources"];
            actions: components["schemas"]["actions"];
            /** @description Pending slot: service, address, house_choice, territory, role, engine_service, document_kind, topic, after_card. */
            awaiting: string | null;
            topic_id: string | null;
            /** @description The reply is the main menu of scenarios. */
            menu: boolean;
            /** @enum {string} */
            dataset_kind: "synthetic" | "user_provided" | "public_reference";
        };
        WebhookAck: {
            /** @constant */
            accepted: true;
        };
        ErrorField: {
            path: string;
            message: string;
        };
        Error: {
            /** @enum {string} */
            code: "INVALID_REQUEST" | "INVALID_DOCUMENT" | "INVALID_PERIOD" | "AUTH_REQUIRED" | "INVALID_MAX_AUTH" | "SESSION_EXPIRED" | "DEMO_DISABLED" | "PREVIEW_DISABLED" | "WEBHOOK_FORBIDDEN" | "NOT_FOUND" | "REVISION_CONFLICT" | "IDEMPOTENCY_CONFLICT" | "INVALID_STATE" | "RECEIPT_NOT_CONFIRMED" | "INCOMPARABLE_RECEIPTS" | "PREVIEW_NOT_READY" | "SOURCE_EXPIRED" | "FILE_TOO_LARGE" | "PAGE_LIMIT_EXCEEDED" | "IMAGE_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "VALIDATION_FAILED" | "WARNINGS_NOT_ACKNOWLEDGED" | "PRIVACY_NOTICE_REQUIRED" | "RATE_LIMITED" | "QUEUE_LIMIT_REACHED" | "SERVICE_UNAVAILABLE" | "ENGINE_UNAVAILABLE" | "PREVIEW_UNAVAILABLE";
            message: string;
            retryable: boolean;
            fields: components["schemas"]["ErrorField"][];
            /** @description Only documented safe fields of this error code; no SQL, stack or paths. */
            details: {
                current_revision?: number;
                reasons?: string[];
            };
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
            request_id: components["schemas"]["Id"];
        };
        /** @description Catalog-specific public metadata may include synthetic and verified channels. */
        CatalogItem: {
            id: string;
            label: string;
        } & {
            [key: string]: unknown;
        };
        DocumentKind: {
            id: string;
            label: string;
            territory_id: string | null;
        };
        /** @description MAX Update envelope per https://dev.max.ru/docs-api/objects/Update. Event-specific fields are retained only as needed and validated per type. No update_id field is assumed. */
        MaxUpdate: {
            update_type: string;
            /**
             * Format: int64
             * @description Unix milliseconds
             */
            timestamp: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * Status
         * @enum {string}
         */
        status: "answered" | "needs_clarification" | "unsupported";
        /** Text */
        text: string;
        /** Topic Id */
        topic_id: string | null;
        /** Steps */
        steps: string[];
        /** SourceRef */
        SourceRef: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
            /** Territory Id */
            territory_id: string | null;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
            /**
             * Review After
             * Format: date-time
             */
            review_after: string;
            /** Content Version */
            content_version: string;
            /** Is Synthetic */
            is_synthetic: boolean;
        };
        /** Sources */
        sources: components["schemas"]["SourceRef"][];
        /** ReceiptRef */
        "$defs-ReceiptRef": {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revision */
            revision: number;
        };
        /** NextAction */
        NextAction: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "open_link" | "prepare_draft" | "select_topic" | "navigate";
            /** Label */
            label: string;
            /** Url */
            url: string | null;
            /** Topic Id */
            topic_id: string | null;
            /** Organization Id */
            organization_id: string | null;
            /** Source Id */
            source_id: string | null;
            /** Target */
            target: ("receipt_upload" | "receipt_history" | "receipt_detail" | "comparison") | null;
            receipt_ref: components["schemas"]["$defs-ReceiptRef"] | null;
            /** Requires */
            requires: string[];
        };
        /** Actions */
        actions: components["schemas"]["NextAction"][];
        /** ClarificationOption */
        ClarificationOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** Clarification */
        Clarification: {
            /**
             * Field
             * @enum {string}
             */
            field: "topic_id" | "territory_id" | "role" | "organization_id" | "service_code" | "document_kind";
            /** Prompt */
            prompt: string;
            /** Options */
            options: components["schemas"]["ClarificationOption"][];
        };
        clarification: components["schemas"]["Clarification"] | null;
        /** Limitations */
        limitations: string[];
        /** Knowledge Version */
        knowledge_version: string;
        receipt_ref: components["schemas"]["$defs-ReceiptRef"] | null;
        /** ServiceLine */
        ServiceLine: {
            /**
             * Line Id
             * Format: uuid
             */
            line_id: string;
            /** Raw Name */
            raw_name: string;
            /**
             * Service Code
             * @enum {string}
             */
            service_code: "cold_water" | "hot_water" | "drainage" | "electricity" | "heating" | "maintenance" | "capital_repair" | "waste" | "other";
            /**
             * Scope
             * @enum {string}
             */
            scope: "individual" | "common_property" | "unspecified";
            /** Unit */
            unit: ("m3" | "kwh" | "gcal" | "m2" | "month" | "person" | "other") | null;
            /** Unit Label */
            unit_label: string | null;
            /** Quantity */
            quantity: string | null;
            /** Tariff */
            tariff: string | null;
            /** Charge Amount */
            charge_amount: string | null;
            /** Supplier Key */
            supplier_key: string | null;
            /** Segment Key */
            segment_key: string | null;
            /**
             * Calculation Kind
             * @enum {string}
             */
            calculation_kind: "simple_product" | "document_amount";
        };
        /** Adjustment */
        Adjustment: {
            /**
             * Adjustment Id
             * Format: uuid
             */
            adjustment_id: string;
            /** Label */
            label: string;
            /** Amount */
            amount: string | null;
            /** Service Line Id */
            service_line_id: string | null;
            /** Related Period */
            related_period: string | null;
        };
        /** Settlement */
        Settlement: {
            /**
             * Formula Kind
             * @enum {string}
             */
            formula_kind: "signed_balance_v1" | "unsupported";
            /** Opening Balance */
            opening_balance: string | null;
            /** Payments Credited */
            payments_credited: string | null;
            /** Penalties */
            penalties: string | null;
            /** Other Account Changes */
            other_account_changes: string | null;
            /** Document Closing Balance */
            document_closing_balance: string | null;
        };
        /** BillData */
        "BillData.schema": {
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
            /** Period */
            period: string | null;
            /**
             * Currency
             * @constant
             */
            currency: "RUB";
            /** Issuer Name */
            issuer_name: string | null;
            /** Provider Id */
            provider_id: string | null;
            /** Account Number */
            account_number: string | null;
            /** Address Text */
            address_text: string | null;
            /** Template Id */
            template_id: string | null;
            /** Template Version */
            template_version: string | null;
            /** Services */
            services: components["schemas"]["ServiceLine"][];
            /** Adjustments */
            adjustments: components["schemas"]["Adjustment"][];
            settlement: components["schemas"]["Settlement"];
            /** Document Current Charges */
            document_current_charges: string | null;
            /** Document Total Due */
            document_total_due: string | null;
            $defs: {
                /** Adjustment */
                Adjustment: {
                    /**
                     * Adjustment Id
                     * Format: uuid
                     */
                    adjustment_id: string;
                    /** Label */
                    label: string;
                    /** Amount */
                    amount: string | null;
                    /** Service Line Id */
                    service_line_id: string | null;
                    /** Related Period */
                    related_period: string | null;
                };
                /** ServiceLine */
                ServiceLine: {
                    /**
                     * Line Id
                     * Format: uuid
                     */
                    line_id: string;
                    /** Raw Name */
                    raw_name: string;
                    /**
                     * Service Code
                     * @enum {string}
                     */
                    service_code: "cold_water" | "hot_water" | "drainage" | "electricity" | "heating" | "maintenance" | "capital_repair" | "waste" | "other";
                    /**
                     * Scope
                     * @enum {string}
                     */
                    scope: "individual" | "common_property" | "unspecified";
                    /** Unit */
                    unit: ("m3" | "kwh" | "gcal" | "m2" | "month" | "person" | "other") | null;
                    /** Unit Label */
                    unit_label: string | null;
                    /** Quantity */
                    quantity: string | null;
                    /** Tariff */
                    tariff: string | null;
                    /** Charge Amount */
                    charge_amount: string | null;
                    /** Supplier Key */
                    supplier_key: string | null;
                    /** Segment Key */
                    segment_key: string | null;
                    /**
                     * Calculation Kind
                     * @enum {string}
                     */
                    calculation_kind: "simple_product" | "document_amount";
                };
                /** Settlement */
                Settlement: {
                    /**
                     * Formula Kind
                     * @enum {string}
                     */
                    formula_kind: "signed_balance_v1" | "unsupported";
                    /** Opening Balance */
                    opening_balance: string | null;
                    /** Payments Credited */
                    payments_credited: string | null;
                    /** Penalties */
                    penalties: string | null;
                    /** Other Account Changes */
                    other_account_changes: string | null;
                    /** Document Closing Balance */
                    document_closing_balance: string | null;
                };
            };
        };
        /** FieldEvidence */
        "FieldEvidence.schema": {
            /** Path */
            path: string;
            /**
             * Source
             * @enum {string}
             */
            source: "pdf_text" | "ocr" | "manual" | "template_default";
            /** Page Number */
            page_number: number | null;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /** Source Text */
            source_text: string | null;
            /** Needs Review */
            needs_review: boolean;
            /** Reason */
            reason: string | null;
        };
        /** Issue */
        "Issue.schema": {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Path */
            path: string | null;
            /** Message */
            message: string;
        };
        /** Issue */
        Issue: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Path */
            path: string | null;
            /** Message */
            message: string;
        };
        /** ReconciliationCheck */
        ReconciliationCheck: {
            /**
             * Field
             * @enum {string}
             */
            field: "document_current_charges" | "document_closing_balance" | "document_total_due";
            /** Document Value */
            document_value: string | null;
            /** Calculated Value */
            calculated_value: string | null;
            /** Difference */
            difference: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "matched" | "mismatch" | "incomplete" | "unsupported";
        };
        /** ExplanationLine */
        ExplanationLine: {
            /**
             * Line Id
             * Format: uuid
             */
            line_id: string;
            /** Title */
            title: string;
            /** Explanation */
            explanation: string;
            /** Formula Text */
            formula_text: string | null;
            /** Calculated Amount */
            calculated_amount: string | null;
            /** Difference */
            difference: string | null;
            /** Issues */
            issues: components["schemas"]["Issue"][];
        };
        /** BalanceComponent */
        BalanceComponent: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Amount */
            amount: string | null;
        };
        /** ReceiptExplanation */
        "ReceiptExplanation.schema": {
            receipt_ref: components["schemas"]["$defs-ReceiptRef"];
            /** Engine Version */
            engine_version: string;
            /** Knowledge Version */
            knowledge_version: string;
            /** Summary */
            summary: string;
            /** Current Charges */
            current_charges: string | null;
            /** Document Total Due */
            document_total_due: string | null;
            /** Calculated Closing Balance */
            calculated_closing_balance: string | null;
            /** Calculated Total Due */
            calculated_total_due: string | null;
            /** Unexplained Difference */
            unexplained_difference: string | null;
            /** Reconciliation Checks */
            reconciliation_checks: components["schemas"]["ReconciliationCheck"][];
            /**
             * Reconciliation Status
             * @enum {string}
             */
            reconciliation_status: "matched" | "mismatch" | "incomplete" | "unsupported";
            /** Lines */
            lines: components["schemas"]["ExplanationLine"][];
            /** Balance Components */
            balance_components: components["schemas"]["BalanceComponent"][];
            /** Issues */
            issues: components["schemas"]["Issue"][];
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /** Actions */
            actions: components["schemas"]["NextAction"][];
            $defs: {
                /** BalanceComponent */
                BalanceComponent: {
                    /** Code */
                    code: string;
                    /** Label */
                    label: string;
                    /** Amount */
                    amount: string | null;
                };
                /** ExplanationLine */
                ExplanationLine: {
                    /**
                     * Line Id
                     * Format: uuid
                     */
                    line_id: string;
                    /** Title */
                    title: string;
                    /** Explanation */
                    explanation: string;
                    /** Formula Text */
                    formula_text: string | null;
                    /** Calculated Amount */
                    calculated_amount: string | null;
                    /** Difference */
                    difference: string | null;
                    /** Issues */
                    issues: components["schemas"]["Issue"][];
                };
                /** Issue */
                Issue: {
                    /** Code */
                    code: string;
                    /**
                     * Severity
                     * @enum {string}
                     */
                    severity: "info" | "warning" | "error";
                    /** Path */
                    path: string | null;
                    /** Message */
                    message: string;
                };
                /** NextAction */
                NextAction: {
                    /** Id */
                    id: string;
                    /**
                     * Type
                     * @enum {string}
                     */
                    type: "open_link" | "prepare_draft" | "select_topic" | "navigate";
                    /** Label */
                    label: string;
                    /** Url */
                    url: string | null;
                    /** Topic Id */
                    topic_id: string | null;
                    /** Organization Id */
                    organization_id: string | null;
                    /** Source Id */
                    source_id: string | null;
                    /** Target */
                    target: ("receipt_upload" | "receipt_history" | "receipt_detail" | "comparison") | null;
                    receipt_ref: components["schemas"]["$defs-ReceiptRef"] | null;
                    /** Requires */
                    requires: string[];
                };
                /** ReceiptRef */
                ReceiptRef: {
                    /**
                     * Id
                     * Format: uuid
                     */
                    id: string;
                    /** Revision */
                    revision: number;
                };
                /** ReconciliationCheck */
                ReconciliationCheck: {
                    /**
                     * Field
                     * @enum {string}
                     */
                    field: "document_current_charges" | "document_closing_balance" | "document_total_due";
                    /** Document Value */
                    document_value: string | null;
                    /** Calculated Value */
                    calculated_value: string | null;
                    /** Difference */
                    difference: string | null;
                    /**
                     * Status
                     * @enum {string}
                     */
                    status: "matched" | "mismatch" | "incomplete" | "unsupported";
                };
                /** SourceRef */
                SourceRef: {
                    /** Id */
                    id: string;
                    /** Title */
                    title: string;
                    /** Url */
                    url: string | null;
                    /** Territory Id */
                    territory_id: string | null;
                    /**
                     * Verified At
                     * Format: date-time
                     */
                    verified_at: string;
                    /**
                     * Review After
                     * Format: date-time
                     */
                    review_after: string;
                    /** Content Version */
                    content_version: string;
                    /** Is Synthetic */
                    is_synthetic: boolean;
                };
            };
        };
        /**
         * Status
         * @enum {string}
         */
        "properties-status": "complete" | "partial" | "needs_identity_confirmation";
        /** PeriodReceiptRef */
        PeriodReceiptRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revision */
            revision: number;
            /** Period */
            period: string | null;
        };
        /** Engine Version */
        engine_version: string;
        /** Delta Current Charges */
        delta_current_charges: string | null;
        /** Delta Adjustments */
        delta_adjustments: string | null;
        /** Delta Total Due */
        delta_total_due: string | null;
        /** ComparedLine */
        ComparedLine: {
            /** Older Line Id */
            older_line_id: string | null;
            /** Newer Line Id */
            newer_line_id: string | null;
            /** Label */
            label: string;
            /**
             * Match Status
             * @enum {string}
             */
            match_status: "matched" | "added" | "removed" | "ambiguous" | "incompatible";
            /** Older Amount */
            older_amount: string | null;
            /** Newer Amount */
            newer_amount: string | null;
            /** Delta */
            delta: string | null;
            /** Quantity Effect */
            quantity_effect: string | null;
            /** Tariff Effect */
            tariff_effect: string | null;
            /** Rounding Effect */
            rounding_effect: string | null;
            /** Explanation */
            explanation: string;
        };
        /** Lines */
        lines: components["schemas"]["ComparedLine"][];
        /** SettlementDelta */
        SettlementDelta: {
            /**
             * Code
             * @enum {string}
             */
            code: "opening_balance" | "payments_credited" | "penalties" | "other_account_changes" | "credit_clamp";
            /** Label */
            label: string;
            /** Raw Delta */
            raw_delta: string | null;
            /** Contribution */
            contribution: string | null;
        };
        /** Settlement Deltas */
        settlement_deltas: components["schemas"]["SettlementDelta"][];
        /** Unexplained Delta */
        unexplained_delta: string | null;
        /** Issues */
        issues: components["schemas"]["Issue"][];
        /** Recipient */
        Recipient: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        recipient: components["schemas"]["Recipient"] | null;
    };
    responses: {
        /** @description Success with no body */
        NoContent: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Session created */
        AuthResult: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthResponse"];
            };
        };
        /** @description Current user */
        Me: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UserAndProfile"];
            };
        };
        /** @description Updated profile */
        Profile: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        /** @description Current aggregate opt-in state */
        AggregateConsent: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AggregateConsentView"];
            };
        };
        /** @description Suppressed or aggregate-only city metric */
        CityComparison: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CityComparisonView"];
            };
        };
        /** @description Fixed synthetic preview metric; never real city statistics */
        PreviewCityComparison: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PreviewCityComparisonView"];
            };
        };
        /** @description Public verified catalog */
        Catalog: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Catalog"];
            };
        };
        /** @description Answer or structured clarification/unsupported */
        Answer: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AnswerView"];
            };
        };
        /** @description Receipt view */
        Receipt: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ReceiptView"];
            };
        };
        /** @description Accepted processing job */
        ReceiptQueued: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ReceiptQueued"];
            };
        };
        /** @description User-owned receipts */
        ReceiptList: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ReceiptList"];
            };
        };
        /** @description Confirmed current revision explanation */
        Explanation: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ReceiptExplanation.schema"];
            };
        };
        /** @description User-owned job */
        Job: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Job"];
            };
        };
        /** @description Complete, partial or identity confirmation result */
        Comparison: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ComparisonView"];
            };
        };
        /** @description Editable draft; no send operation */
        Draft: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DraftView"];
            };
        };
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Missing or invalid session */
        Unauthorized: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Revision, idempotency or state conflict */
        Conflict: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        SourceExpired: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description File, page or image exceeds limit */
        PayloadTooLarge: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Invalid fields or unacknowledged warning */
        ValidationFailed: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rate or queue limit; Retry-After supplied. */
        RateLimited: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Temporary service or engine failure */
        ServiceUnavailable: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Safe structured error envelope; see HTTP/code mapping in spec §7.1. */
        ErrorResponse: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Id: components["schemas"]["Id"];
        Page: number;
        Revision: number;
        Cursor: string;
        Limit: number;
        /** @description UUID, result retained 24 hours; reuse with different body returns 409. */
        IdempotencyKey: components["schemas"]["Id"];
    };
    requestBodies: never;
    headers: {
        /** @description Correlation UUID; contains no user or document data. */
        RequestId: components["schemas"]["Id"];
        /** @description Seconds before retry. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public version, notice, limits and feature flags; no secrets. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    authenticateMax: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaxAuthRequest"];
            };
        };
        responses: {
            200: components["responses"]["AuthResult"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    authenticateDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoAuthRequest"];
            };
        };
        responses: {
            200: components["responses"]["AuthResult"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    authenticatePreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuthResult"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Me"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            200: components["responses"]["Profile"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    updateAggregateConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AggregateConsentRequest"];
            };
        };
        responses: {
            200: components["responses"]["AggregateConsent"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Catalog"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            200: components["responses"]["Answer"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Answer"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    assistantDialog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogRequest"];
            };
        };
        responses: {
            /** @description Dialogue reply; unknown or unsupported questions are successful structured results. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogReply"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listReceipts: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ReceiptList"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadReceipt: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID, result retained 24 hours; reuse with different body returns 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description PDF, JPEG or PNG; at most 10 MiB
                     */
                    file: string;
                    /**
                     * @description Optional explicit built-in synthetic sample ID; exact bytes and SHA-256 must match the manifest or 422. OCR still processes uploaded bytes.
                     * @enum {string}
                     */
                    demo_sample_id?: "demo-bill-2026-08.pdf" | "demo-bill-2026-09.pdf";
                };
            };
        };
        responses: {
            202: components["responses"]["ReceiptQueued"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createManualReceipt: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID, result retained 24 hours; reuse with different body returns 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualReceiptRequest"];
            };
        };
        responses: {
            201: components["responses"]["Receipt"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    importDemoReceipt: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID, result retained 24 hours; reuse with different body returns 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoReceiptRequest"];
            };
        };
        responses: {
            202: components["responses"]["ReceiptQueued"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    getReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Receipt"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getCityComparison: {
        parameters: {
            query: {
                service_code: string;
                metric: "charge_amount" | "tariff";
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CityComparison"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getPreviewCityComparison: {
        parameters: {
            query: {
                service_code: string;
                metric: "charge_amount" | "tariff";
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PreviewCityComparison"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    editReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditReceiptRequest"];
            };
        };
        responses: {
            200: components["responses"]["Receipt"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    confirmReceipt: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID, result retained 24 hours; reuse with different body returns 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmReceiptRequest"];
            };
        };
        responses: {
            200: components["responses"]["Receipt"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    retryReceipt: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID, result retained 24 hours; reuse with different body returns 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryReceiptRequest"];
            };
        };
        responses: {
            202: components["responses"]["ReceiptQueued"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            410: components["responses"]["SourceExpired"];
            429: components["responses"]["RateLimited"];
        };
    };
    explainReceipt: {
        parameters: {
            query: {
                revision: components["parameters"]["Revision"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Explanation"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getReceiptSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original document bytes. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    /** @description Attachment filename */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["SourceExpired"];
        };
    };
    getReceiptPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                page: components["parameters"]["Page"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Safe raster preview. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            410: components["responses"]["SourceExpired"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Job"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    compareReceipts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            200: components["responses"]["Comparison"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID, result retained 24 hours; reuse with different body returns 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            201: components["responses"]["Draft"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Draft"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    editDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditDraftRequest"];
            };
        };
        responses: {
            200: components["responses"]["Draft"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    receiveMaxWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaxUpdate"];
            };
        };
        responses: {
            /** @description Accepted or duplicate event; processing is asynchronous. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
